import React from 'react';
import { Check, MapPin, Pause } from 'lucide-react';
const format = secs => `${Math.floor(Math.max(0, secs) / 60)}:${String(Math.max(0, secs) % 60).padStart(2, '0')}`;
export default function FieldAlertFeed({ dispatches = [], now, onNavigate, onAccept, onDefer }) {
  const live = [...dispatches].sort((a, b) => new Date(a?.sla_deadline || 0) - new Date(b?.sla_deadline || 0));
  return <div className="space-y-3">{live.map(item => { const deadline = (item?.sla_deadline || '').replace(' ', 'T'); const deadlineMs = new Date(deadline).getTime(); const remaining = Number.isFinite(deadlineMs) ? Math.ceil((deadlineMs - now) / 1000) : 0; return <article key={item?.dispatch_id || item?.alert_id || 'unknown-dispatch'} className="rounded-xl border border-red-500/35 bg-gradient-to-br from-red-500/10 to-[#111827] p-4 shadow-lg animate-[pulse_3s_ease-in-out_infinite]">
    <div className="flex justify-between gap-2"><span className="text-[10px] font-mono font-bold text-red-300 bg-red-500/15 border border-red-500/30 px-2 py-1 rounded">CRITICAL DISPATCH</span><span className="text-xs font-mono text-red-200">{remaining <= 0 ? 'SLA BREACHED' : `${format(remaining)} remaining`}</span></div>
    <h2 className="mt-3 text-base font-semibold text-white">{item?.case_id || item?.alert_id || 'Unassigned case'} <span className="font-normal text-slate-400">• {item?.city || 'Location pending'}</span></h2><div className="mt-1 text-2xl font-bold text-emerald-300">₹{Number(item?.amount || 0).toLocaleString('en-IN')}</div>
    <div className="mt-2 flex gap-4 text-xs text-slate-400"><span>{item?.distance_km ?? '--'} km away</span><span>ETA {item?.eta_minutes ?? '--'} min</span><span>{(item?.status || 'PENDING').replace('_', ' ')}</span></div>
    <div className="grid grid-cols-3 gap-2 mt-4"><button onClick={() => onNavigate(item)} className="min-h-11 rounded-lg bg-cyan-600 text-white text-xs font-semibold flex items-center justify-center gap-1"><MapPin className="w-4 h-4" />Navigate</button><button onClick={() => onAccept(item)} className="min-h-11 rounded-lg bg-emerald-600/80 text-white text-xs font-semibold flex items-center justify-center gap-1"><Check className="w-4 h-4" />Accept</button><button onClick={() => onDefer(item)} className="min-h-11 rounded-lg bg-slate-800 border border-slate-700 text-slate-200 text-xs font-semibold flex items-center justify-center gap-1"><Pause className="w-4 h-4" />Defer</button></div>
  </article>; })}{!live.length && <div className="text-center py-16 text-slate-500 text-sm">No active dispatches. Field terminal standing by.</div>}</div>;
}
